### ISSUE TITLE
朋友愿望列表接口没有愿望到期时间，没有愿望标题，（愿望的标题，不是愿望项标题）

### ISSUE THREAD

**Issue by sohaha** [abigail830/togetherm#10]
```
[
              {
                asofMonth: "2028年12月",
                wishListDTOList: [
                  {
                    wishID: 85,
                    wishListID: 24,
                    wishStatus: "DONE",
                    listId: 82,
                    description: "吃大餐",
                    listDescription: "我的愿望是什么",
                    listDueTime: "2028-12-19 00:59:59",
                    dateInMonth: "19",
                    yearAndMonth: "2028-12"
                  },
                  {
                    wishID: 85,
                    wishListID: 24,
                    wishStatus: "TAKEUP",
                    listId: 82,
                    description: "吃大餐222",
                    listDescription: "我的愿望是什么",
                    listDueTime: "2028-12-19 00:59:59",
                    dateInMonth: "19",
                    yearAndMonth: "2028-12"
                  }
                ]
              }
            ]
```

**Comment by sohaha** [comment]
![image](https://user-images.githubusercontent.com/18098083/50382155-d43acc00-06d3-11e9-8bc6-063e7e1dd52e.png)

**Comment by abigail830** [comment]
@sohaha 上面的建议的json不是很对，
- description: "吃大餐",  -》按照例图这里应该是显示原来提出愿望的主人
- listDescription: "我的愿望是什么", -》这里也不应该显示愿望清单的标题，而应该是这个implementor takeup的那个wish的名称

**Comment by abigail830** [comment]
@bryan-cheung 按之前微信说的，现在返回的结果里面已经有了愿望主人和那个takeup的wish内容，欠缺的是左边时间轴的对应信息，就是那个愿望清单的dueTime，和需要排序，排序方式和“我的愿望”一样

**Comment by sohaha** [comment]
@bryan-cheung @abigail830 需要及时确定好,要定义好数据格式,不然朋友愿望的时间轴无法开发下去

**Comment by bryan-cheung** [comment]
https://wishlist.rabbit-hop.com/v1/wishes/taken/timeline?openId=oEmJ75YWmBSDgyz4KLi_yGL8MBV4

{
  "takenWishTimelineEntryList": [
    {
      "asofMonth": "2018年11月",
      "takenWishDTOList": [
        {
          "wishID": 76,
          "wishListID": 22,
          "description": "Microservices",
          "createTime": "2018-12-05",
          "lastUpdateTime": "2018-11-05",
          "wishStatus": "DONE",
          "implementor": null,
          "creator": {
            "openId": "oEmJ75YWmBSDgyz4KLi_yGL8MBV4",
            "gender": "2.0",
            "nickName": "SAraQian",
            "city": null,
            "country": null,
            "province": null,
            "language": "zh_TW",
            "avatarUrl": "https://wx.qlogo.cn/mmopen/vi_32/8icO8sustxOendXVn9ChOsQ1MGC1p08H3OZOQrwXOzn3psspneKPloFgZJYe502tSOiahoRTvpzWbn349tH1X0Zg/132"
          },
          "listDueTime": "2018-11-05",
          "dateInMonth": "05",
          "yearAndMonth": "2018-11"
        },
        {
          "wishID": 77,
          "wishListID": 22,
          "description": "Java",
          "createTime": "2018-11-05",
          "lastUpdateTime": "2018-11-05",
          "wishStatus": "TAKEUP",
          "implementor": null,
          "creator": {
            "openId": "oEmJ75YWmBSDgyz4KLi_yGL8MBV4",
            "gender": "2.0",
            "nickName": "SAraQian",
            "city": null,
            "country": null,
            "province": null,
            "language": "zh_TW",
            "avatarUrl": "https://wx.qlogo.cn/mmopen/vi_32/8icO8sustxOendXVn9ChOsQ1MGC1p08H3OZOQrwXOzn3psspneKPloFgZJYe502tSOiahoRTvpzWbn349tH1X0Zg/132"
          },
          "listDueTime": "2018-11-05",
          "dateInMonth": "05",
          "yearAndMonth": "2018-11"
        },
        {
          "wishID": 79,
          "wishListID": 22,
          "description": "New wish",
          "createTime": "2018-11-05",
          "lastUpdateTime": "2018-11-05",
          "wishStatus": "TAKEUP",
          "implementor": null,
          "creator": {
            "openId": "oEmJ75YWmBSDgyz4KLi_yGL8MBV4",
            "gender": "2.0",
            "nickName": "SAraQian",
            "city": null,
            "country": null,
            "province": null,
            "language": "zh_TW",
            "avatarUrl": "https://wx.qlogo.cn/mmopen/vi_32/8icO8sustxOendXVn9ChOsQ1MGC1p08H3OZOQrwXOzn3psspneKPloFgZJYe502tSOiahoRTvpzWbn349tH1X0Zg/132"
          },
          "listDueTime": "2018-11-05",
          "dateInMonth": "05",
          "yearAndMonth": "2018-11"
        },
        {
          "wishID": 81,
          "wishListID": 22,
          "description": "Adobe",
          "createTime": "2018-11-27",
          "lastUpdateTime": "2018-11-05",
          "wishStatus": "DONE",
          "implementor": null,
          "creator": {
            "openId": "oEmJ75YWmBSDgyz4KLi_yGL8MBV4",
            "gender": "2.0",
            "nickName": "SAraQian",
            "city": null,
            "country": null,
            "province": null,
            "language": "zh_TW",
            "avatarUrl": "https://wx.qlogo.cn/mmopen/vi_32/8icO8sustxOendXVn9ChOsQ1MGC1p08H3OZOQrwXOzn3psspneKPloFgZJYe502tSOiahoRTvpzWbn349tH1X0Zg/132"
          },
          "listDueTime": "2018-11-05",
          "dateInMonth": "05",
          "yearAndMonth": "2018-11"
        },
        {
          "wishID": 82,
          "wishListID": 22,
          "description": "If",
          "createTime": "2018-11-06",
          "lastUpdateTime": "2018-11-05",
          "wishStatus": "TAKEUP",
          "implementor": null,
          "creator": {
            "openId": "oEmJ75YWmBSDgyz4KLi_yGL8MBV4",
            "gender": "2.0",
            "nickName": "SAraQian",
            "city": null,
            "country": null,
            "province": null,
            "language": "zh_TW",
            "avatarUrl": "https://wx.qlogo.cn/mmopen/vi_32/8icO8sustxOendXVn9ChOsQ1MGC1p08H3OZOQrwXOzn3psspneKPloFgZJYe502tSOiahoRTvpzWbn349tH1X0Zg/132"
          },
          "listDueTime": "2018-11-05",
          "dateInMonth": "05",
          "yearAndMonth": "2018-11"
        }
      ]
    }
  ]
}

**Comment by abigail830** [comment]
@bryan-cheung listDueTime应该有时分秒的哦～

**Comment by bryan-cheung** [comment]
fixed listDueTime timestamp format
