### ISSUE TITLE
接通通知模版

### ISSUE THREAD

**Issue by cjr100week** [abigail830/togetherm#11]
模板ID
iOYn0MAVCf5w9bdy5V3aA_jA_-f2xXt9uTRE5_pggt4
复制
标题领取成功通知
关键词姓名{{keyword1.DATA}}
备注{{keyword2.DATA}}
@SAraQian 那你可以用来用到后台发送模版信息了：）

**Comment by abigail830** [comment]
@bryan-cheung 模版还是开名吧，因为栏目写了姓名
姓名：nickName of implementor
备注：您的【清单名】-【愿望名】被朋友领取啦！
