### ISSUE TITLE
愿望详情接口数据缺失,导致无法实现 愿望到期的状态

### ISSUE THREAD

**Issue by sohaha** [abigail830/togetherm#17]
朋友愿望列表里的implementor(我理解为get的人)不管状态是什么始终是null
![image](https://user-images.githubusercontent.com/18098083/50469198-5a158a80-09e6-11e9-9865-1dbf71a7d646.png)

**Comment by bryan-cheung** [comment]
朋友愿望列表是哪个界面，用哪个endpoint？

**Comment by abigail830** [comment]
![image](https://user-images.githubusercontent.com/19251334/50543949-9680fa80-0c21-11e9-90f4-93101dff1fc2.png)
@sohaha 看起来是测试数据问题，试试在友的愿望页面好了之后重新用新数据走一次看看
