### ISSUE TITLE
【首页】页面更改

### ISSUE THREAD

**Issue by abigail830** [abigail830/togetherm#21]
1.创建清单 改成 创建契约
2.时间轴时间
3.我的清单 友的清单 改成 我的契约 友的契约
4.没被选中的时候 get 0个 也是灰色
查看20181230版本ui

**Comment by sohaha** [comment]
@abigail830 4. 没被选中的时候 get 0个 也是灰色 是什么意思,不明白

**Comment by sohaha** [comment]
@abigail830 友的清单的时间轴接口完成之后在把issue丢回我吧

**Comment by abigail830** [comment]
@sohaha 灰色我也不知道啥意思～不过丹丹说不纠结就先不管了～
友的愿望接好了，界面还要调整的是
- 和“我的愿望”统一
- 时间点显示
