### ISSUE TITLE
线下试投放，根据不同的活动，需要有不同的海报。所以每个活动，要有专属入口，每个入口有该活动的专属海报及小程序码。不影响现有版本正常使用。

### ISSUE THREAD

**Issue by youdandan** [abigail830/togetherm#37]
目前需要三个入口
1.原有入口
2.天硕光大活动入口
3.兔叮贺年专用入口

**Comment by cjr100week** [comment]
原有入口正常进入；


天硕入口：
![image](https://user-images.githubusercontent.com/37078626/50645875-98471700-0faf-11e9-9447-cb9213aef19e.png)

兔叮入口：
![image](https://user-images.githubusercontent.com/37078626/50645839-79e11b80-0faf-11e9-87ad-f11662b7845e.png)

**Comment by cjr100week** [comment]
也可以手动生成小程序码的，跳转到制定路径。
index_new/index_new?entrance=dt
以及
index_new/index_new?entrance=ts
需要的时候可以assign到我去生成。
需要用到access token，用到app id和secret可以贴在issue转交或者邮件交代：）
