### ISSUE TITLE
【春节活动卡券逻辑】-后端

### ISSUE THREAD

**Issue by youdandan** [abigail830/togetherm#46]
![image](https://user-images.githubusercontent.com/46134834/51083422-0381ad80-1755-11e9-8d14-d1e21d9bbd78.png)

**Comment by abigail830** [comment]
https://github.com/abigail830/togetherm/issues/48
https://github.com/abigail830/togetherm/issues/47
https://github.com/abigail830/togetherm/issues/49
https://github.com/abigail830/togetherm/issues/50
