### ISSUE TITLE
获取我答应列表的接口需要返回该契约认证人是否创建者

### ISSUE THREAD

**Issue by sohaha** [abigail830/togetherm#87]
<img width="1381" alt="Snipaste_2019-04-01_18-37-44" src="https://user-images.githubusercontent.com/18098083/55322006-a83a9e00-54ad-11e9-8aaf-c12872f7bf8d.png">
不然前端无法控制完成按钮

**Comment by abigail830** [comment]
@bryan-cheung 需要新功能，在GET /v1/wishes/taken/timeline
getTakenUpWishTimeline那个接口，就是”友的愿望“列表，需要join上wishlist里面那个isSelfWittness，因为功能需要分辨谁有权利去mark complete

**Comment by abigail830** [comment]
@sohaha 完成，请测试
