### ISSUE TITLE
契约详情接口数据错误 isSelfWitness 为 null

### ISSUE THREAD

**Issue by sohaha** [abigail830/togetherm#88]
<img width="953" alt="Snipaste_2019-04-01_18-46-15" src="https://user-images.githubusercontent.com/18098083/55322294-855cb980-54ae-11e9-92b4-91cb44f0f9b6.png">
isSelfWitness 的值

**Comment by abigail830** [comment]
我刚尝试创建契约，1254： isSelfWitness=true, 1255: isSelfWitness=false， 没有发现问题，
是怎么样会出现null的场景？
@sohaha
