### ISSUE TITLE
印记功能接口

### ISSUE THREAD

**Issue by sohaha** [abigail830/togetherm#90]

**Comment by abigail830** [comment]
![image](https://user-images.githubusercontent.com/19251334/56503885-6bf8db80-6549-11e9-9d18-9471e72e1601.png)

**Comment by abigail830** [comment]
@sohaha 看这样的接口够不够用？
- 左边“谁最宠你”：返回统计别人takeup并完成的 我的愿望个数 - 前五位
- 左边“你最宠谁”：返回统计我takeup并完成的 别人的愿望个数 - 前五位

**Comment by abigail830** [comment]
@sohaha 按群里讨论，友爱印记先缓一缓，可以把首页那个menu先隐藏一下
